services:
  - type: web
    name: market-anxk
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /status
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: TELEGRAM_GATEWAY_API_KEY
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: WHATSAPP_PAIRING_NUMBER
        sync: false
