services:
  - type: web
    name: aye-whatsapp-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 8001
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_ADMIN_CHAT_ID
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        sync: false
